#!/bin/bash
set -e
P=$PATH
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

export JAVA_HOME="$DIR/jdk8"
export PATH="$JAVA_HOME/bin:$P"
cd native
../mvnw clean install
cd ..

export JAVA_HOME="$DIR/jdk11"
export PATH="$JAVA_HOME/bin:$P"
cd common
../mvnw clean install
cd ..

cd assembly
../mvnw clean package

export PATH="$P"